version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "SHA256:N14dawQw0mkucf+EuKqi98Z124GNapu4gc+yKHkaR9M"
      - run:
          name: Build Docker Image
          command: |
            sed -i "s|ARG SHA=\"\"|ARG SHA=\"$(git log | grep ^commit | head -n 2 | awk 'END{print $2}' | cut -b 1-7)\"|" scripts/Dockerfile 
            cat scripts/Dockerfile | grep "ARG SHA"
            docker build -t $IMAGE_NAME scripts
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
            docker tag $IMAGE_NAME ${IMAGE_NAME}:$(cat src/version.h | grep "#define VERSION " | awk '{gsub("\"","");print $3}' | cut -b 2-)-$(git log | grep ^commit | head -n 2 | awk 'END{print $2}' | cut -b 1-7)
            docker push ${IMAGE_NAME}:$(cat src/version.h | grep "#define VERSION " | awk '{gsub("\"","");print $3}' | cut -b 2-)-$(git log | grep ^commit | head -n 2 | awk 'END{print $2}' | cut -b 1-7)
      - run:
          name: Deploy
          command: |
            ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
            ssh $USER@$HOST < scripts/deploy.sh
            curl -L https://uich.cc/notify | bash
